spring:
  application:
    name: provide
  datasource:
    url: jdbc:mysql://db1:3306/spring_boot_cloud_003?serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8001
version: version01-在本地改的